//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evncpc.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int bill_id { get; set; }
        public string payment { get; set; }
        public string duration { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
