//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evncpc.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class submenu
    {
        public int submenu_id { get; set; }
        public string sub_menu { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public Nullable<int> mainmenu_id { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual mainmenu mainmenu { get; set; }
        public virtual role role { get; set; }
    }
}
