//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Evncpc.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {

        public int UserID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name is required")]
        public String FirstName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Last Name is required")]
        public String LastName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "UserName is required")]
        public String UserName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Email is required")]
        [DataType(DataType.EmailAddress)]
        public String Email { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public String Password { get; set; }
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Password and Confirm Password should be same")]
        public String ConfirmPassword { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}
