//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evncpc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class user
    { 
        public int userid { get; set; }
        [Required(ErrorMessage ="This information is required")]
        public string username { get; set; }
        [Required(ErrorMessage = "This information is required")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string pass { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        [Compare("pass")]
        public string confirmpassword { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    }
}
